version: '3.8'

services:
  unfolder-test:
    build:
      context: .
      dockerfile: test-Dockerfile
    container_name: unfolder-test
    environment:
      - K_FACTOR=0.38
      - OUTPUT_DIR=/app/output
    volumes:
      - ./:/app/brain
      - ../unfolder/src:/app/src
      - ./output:/app/output
    working_dir: /app
    command: tail -f /dev/null  # Keep container running for testing