name: yamuna-manufacturing
services:
  # Step-converter webhook service (replaces EC2 PM2 service)
  - name: step-converter
    image:
      repository: yamuna-step-converter
      tag: latest
    port: 3000
    build:
      method: docker
      context: ./step-converter
      dockerfile: ./Dockerfile
    env:
      - name: PORT
        value: "3000"
      - name: SUPABASE_URL
        value: "https://pynaxyfwywlqfvtjbtuc.supabase.co"
      - name: SUPABASE_KEY
        value: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB5bmF4eWZ3eXdscWZ2dGpidHVjIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc0ODIwNzYxNiwiZXhwIjoyMDYzNzgzNjE2fQ.2jv211NlxOdDcbtE6GxGl7kg38JxvwWZx1sPz9HtzBg"
      - name: UNFOLDER_SERVICE_URL
        value: "http://unfolder:8080"
    resources:
      cpu: 500m
      memory: 1Gi
    autoscaling:
      enabled: true
      min_replicas: 1
      max_replicas: 3
      target_cpu: 70
    domains:
      - name: step-converter
        
  # Unfolder service (STEP to DXF conversion)
  - name: unfolder
    image:
      repository: yamuna-unfolder
      tag: latest
    port: 8080
    build:
      method: docker
      context: ./unfolder
      dockerfile: ./Dockerfile
    env:
      - name: K_FACTOR
        value: "0.38"
      - name: PORT
        value: "8080"
    resources:
      cpu: 2000m
      memory: 4Gi
    autoscaling:
      enabled: true
      min_replicas: 1
      max_replicas: 2
      target_cpu: 80

  # Nester service (AI-powered nesting optimization)
  - name: nester
    image:
      repository: yamuna-nester
      tag: latest
    port: 8080
    build:
      method: docker
      context: ./nester
      dockerfile: ./Dockerfile
    env:
      - name: COLLISION_BUFFER
        value: "7.0"
      - name: SHEET_WIDTH
        value: "1000"
      - name: SHEET_HEIGHT
        value: "500"
      - name: PORT
        value: "8080"
    resources:
      cpu: 1000m
      memory: 2Gi