name: yamuna-manufacturing
services:
  # Unfolder service (STEP to DXF conversion)
  unfolder:
    type: web
    image:
      repository: yamuna-unfolder
      tag: latest
    port: 8080
    build:
      method: docker
      context: ./unfolder
      dockerfile: ./Dockerfile
    source:
      type: local
    env:
      K_FACTOR: "0.38"
      PORT: "3000"
      SUPABASE_URL: "https://pynaxyfwywlqfvtjbtuc.supabase.co"
      SUPABASE_KEY: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB5bmF4eWZ3eXdscWZ2dGpidHVjIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc0ODIwNzYxNiwiZXhwIjoyMDYzNzgzNjE2fQ.2jv211NlxOdDcbtE6GxGl7kg38JxvwWZx1sPz9HtzBg"
    resources:
      cpu: 2000m
      memory: 4Gi
    autoscaling:
      enabled: true
      min_replicas: 1
      max_replicas: 2
      target_cpu: 80