version: '3.8'

services:
  cutter-coder:
    build: .
    container_name: cutter-coder
    ports:
      - "8001:8000"
    volumes:
      - ./input:/app/input
      - ./output:/app/output
    environment:
      - LOG_LEVEL=INFO
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3