services:
  brain:
    build: .
    container_name: brain
    environment:
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_KEY=${SUPABASE_KEY}
      - NODE_ENV=production
      - PYTHONPATH=/app/src
    volumes:
      # Mount .env file for local development
      - ./.env:/app/.env:ro
      # Mount output directory for nesting results
      - ./nesting_output:/tmp/nesting_output
    networks:
      - default

networks:
  default:
    driver: bridge